export const SAVE_TASK = 'SAVE_TASK';
export const GET_ALL_TASKS = 'GET_ALL_TASKS';
export const POSTPONE_TASK = 'POSTPONE_TASK';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const UNCOMPLETED_TASK = 'UNCOMPLETED_TASK';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const DELETE_TASK = 'DELETE_TASK';
